### ISSUE TITLE
提案（検討依頼）ゲームスピード調整

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#10]
ゲーム進行速度を調整できるとうれしいです。
それほど細かい制御はいらないですが、超速、速め、等速、遅め、超遅、ぐらいを
ショートカットキーかなにかでプレイ中に切り替えられるとありがたいです。

**Comment by beta1139** [comment]
テンキーのプラス、テンキーのマイナスで処理速度変更できるようにしました。
config_CS.exeでvsyncをoffにした状態で試してみてください。
