### ISSUE TITLE
ウォールマーケットの煙に関して

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#11]
以前(リビジョン604)セルフ対処していた煙の問題があるんですが、
毎回使えるわけじゃないので、ちょっとお尋ねします。

現在MAP072は、一部（薬屋の屋根～定食屋の正面等）だけ、上層や中層に指定していますが、
従来の全部下層だと煙がキャラの下を通ってしまっていました。
ちなみにその際、煙をfront指定しても駄目でした。
これってやっぱりバグでしょうか？

不思議なのが、 (x11.y26)など、最初は煙がキャラの上に行ってるんだけど、
途中から下に隠れるという・・・よく分からん感じなんですよねｗ

**Comment by beta1139** [comment]
ああ、npc_eventになってるから、slideで歩かせたときに、
１CHIP分歩ききったタイミングでマップデータの階層情報を読んで、自分の階層にセットしてしまってます。

＞不思議なのが、 (x11.y26)など、最初は煙がキャラの上に行ってるんだけど、
歩き始めの１ＣＨＩＰ分はスクリプトのset_layer 7296 frontが有効になってて、
キャラの手前に表示されてるんですが、1CHIP歩ききったタイミングでマップデータの階層情報を読んで
backになっちゃって途中から下に隠れてますね。

とりあえず、
set_ignore_map_layer_flag id flag
という命令を作って、
set_ignore_map_layer 7296 1
として、煙がfrontのままにするようにしときました。
