### ISSUE TITLE
エンカウントとdraw_image(バグ：優先度高)

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#12]
一度でもエンカウントを経た後にdraw_imageをすると、
マップの裏に画像が隠れて、正しく表示されなくなるようです。

**Comment by beta1139** [comment]
戦闘に入って敵画像を読み込むときにR:0x00,G:0x00,B:0x00の色で抜き色を指定する処理が走ってて、
その後、戦闘が終わってもR:0x00,G:0x00,B:0x00の抜き色指定が残ってました。
これが原因かと思ったので、画像を読み込んだ後で、
抜き色をR:0x01,G:0x01,B:0x01に指定する処理を実行するようにしてコミットしましたが、
改善されましたでしょうか。
とりあえず、デバッグエリアの左上のばあさんに話しかけてdraw_imageする処理では改善を確認しました。

**Comment by i7-FF7FC** [comment]
ああ黒にマスク掛かってたんですね、言われてみればそうか。
無事解決しました！ありがとうございます。
今回のイベは結構画像使ってるんでヤバイなと思ってましたｗ
