### ISSUE TITLE
要望（優先度中）テスト用セーブデータ

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#13]
翻訳時にアイテム名やコマンド名など実際にメニュー画面やバトル画面
での見え方を確認したいので、全部入りセーブデータ（メンバー全員そろってる、
持ち物を全部持っている、コマンド・魔法・技などは全て使えるレベルに達している）
を作っていただけないでしょうか。メニューがいじれてあとは強制エンカウント
でバトル画面に入れればいいのでセーブデータとしてのつじつまが合ってなくても
大丈夫です（ミッドガルですでにメンバー全員とかw）。

**Comment by i7-FF7FC** [comment]
スクリプトファイル用意しました。
これを解凍してできたtxtファイルをscript_e\001フォルダに突っ込んでください。
なお上書きする前に、前のファイルはバックアップお願いします。
タマネギ剣士に話しかえるとメンバー交代できます。(phsはまだ対応されてなかったので)
ちなみに、アイテム欄は数多すぎてバグってますね。。
http://ux.getuploader.com/FF7FC_up/download/44/ff7fc_max.zip
PASS:ff7fc

**Comment by beta1139** [comment]
デバッグ用ワープ装置からフィールドに移動する際に、
フルメンバー化　＆　フルアイテム所持するようにスクリプト修正しときました
