### ISSUE TITLE
検討：アイテムメニュー画面構成

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#14]
アイテムメニューで、アイテムやキーアイテムを選択する場合の選択領域（画面下３分の２）で
アイテム名が左右２列に並ぶようになっています。右の列だと12文字分ですが、左の列では14
文字分まで表示できる余地があります。
（アイテムの場合：＞＞はカーソルが描画される位置）
‖＞＞あいてむめいしょう：９９□□＞＞あいてむめいしょう：９９‖
（キーアイテムの場合：＞＞はカーソルが描画される位置）
‖＞＞きー　あいてむめいしょう□□＞＞きー　あいてむめいしょう‖

右の列の表示位置／カーソル描画位置を１文字分左にずらすことはできないでしょうか？
そうするとアイテム名10文字、キーアイテム名13文字まで使えるようになるのですが…
‖＞＞あいてむめいしょう＋：９９＞＞あいてむめいしょう＋：９９‖
‖＞＞きー　あいてむめいしょう＋＞＞きー　あいてむめいしょう＋‖

アイテム名は延ばすとバトルで使うときのメニューとかにも影響がでるのかな？

**Comment by ff7fc-translate** [comment]
まほうメニューの召還魔法選択部分も縦２列構成のメニューなので同じかな？

**Comment by ff7fc-translate** [comment]
魔法メニューとバトル内のアイテムメニューは
メインのアイテムメニューより左右１文字分ずつ狭いんですね。
なので、通常アイテム名は9文字、召還魔法名は12文字で限界でした。

キーアイテムメニューのみ検討していただければ。

**Comment by beta1139** [comment]
メニューのアイテム名、キーアイテム名、召還魔法名の表示位置をずらしました
