### ISSUE TITLE
検討：マテリアメニュー画面

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#15]
マテリアメニューで、装着するマテリアを選択するメニュー（画面右下領域）は、
名称が8文字まで表示できる幅になっています。
実際に装着されたものが表示される部分（画面左下領域）にはマテリア名を9文字
まで描画できる幅があります。
データとして持たせるマテリア名は最大9文字にして、マテリア選択メニューには
最大8文字まで描画、それが選択／装着された場合はフルで9文字まで描画する、
みたいなのはだめでしょうか？

**Comment by ff7fc-translate** [comment]
補足説明です：
↓のサンプル画面で言う Alexander のところです。
http://ux.getuploader.com/FF7FC_up/download/48/materia-menu.png

左側のマテリア情報ペインではAlexanderがちゃんと表示されていますが、
右側の選択ペインでは最後の r が枠線にかぶっています。
選択ペインではこの最後の r を描画せずに "Alexande" と表示、
情報ペインでは振る表示するようにできないか、ということです。

**Comment by beta1139** [comment]
ああ、そこね
Alexand‥
ってしようかなー、と考えてたことがある。
そもそも日本語版でも入りきってないのがあるっていうｗ

**Comment by beta1139** [comment]
マテリア名が8文字を超える場合は、８文字目を…にして枠からはみ出ないよう修正しました
