### ISSUE TITLE
画面のモノクロ処理

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#16]
以前、パレットチェンジはちょっと考えてないというコメントを頂きましたが、
一様にグレイスケールにすることも無理っぽいですかね？
FF3にてエンカウント時の処理や、イベントでエリアが矢に打たれる瞬間のエフェクトなど
色々分析してたら、1フレームや2フレームごとにモノクロになってたんで、
これ実装できないだろうか？と思った次第です。

**Comment by beta1139** [comment]
set_gray_scale/reset_gray_scale命令を追加しました
