### ISSUE TITLE
バトル画面魔法メニュー幅

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#17]
バトル画面の魔法メニュー幅ですが、右にあと１文字分だけ広げられると
魔法名に5文字使えるようになって、英語版が非常に嬉しいのですが…

↓のサンプルの右半分みたいにするのは無理でしょうか？（左半分が現在の形）
http://ux.getuploader.com/FF7FC_up/download/47/battle-item.png

**Comment by beta1139** [comment]
その方向でやります

**Comment by beta1139** [comment]
修正完
