### ISSUE TITLE
SEのループタグ

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#18]
タイトル通りなんですが、SEもループタグ読めるようになりませんかね？
風のSEをループさせるため、導入部とループ部分とに分けて鳴らしてみたんですが、
うーん。。切り替わる時に刹那ながら繋ぎ目出来ちゃうな。。と
ま意識して聞かなきゃ分からんレベルなんですがｗ

**Comment by beta1139** [comment]
play_se_loopもループの開始タグを読んでループ処理するように修正しました
