### ISSUE TITLE
提案（要望：優先度低）英語モード用フォント

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#2]
英語モード用に英数字フォントを微調整したtext_e.bmpを作成してみました。
モード切り替え時に、フォントも切り替えられるとうれしいです。
英数文字の縦位置が若干ずれていてかな文字との共存には向かないので
英語モード専用にした方が良いと思います（一部記号も英語向きに調整してますし）

**Comment by beta1139** [comment]
英語版のときはtext_e.bmpを読み込むように修正しました
