### ISSUE TITLE
原因不明のアプリエラー

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#21]
イベントの続きを作るついでに、既存のウォールマーケットのスクリプトをちょっと変更したのですが、
その際、以下のデバッグファイルから飛んで、MAP071の(x7,y2)からウォールマーケットに入ると、
「FF7FC.exeは動作を停止しました」とのダイアログが出るようになりました。
http://ux.getuploader.com/FF7FC_up/download/49/ichibangai_station_baret.txt

原因を突き詰めようとしたんですが、これが困ったことに、
というより不思議なんですが、落ちるのと落ちないパターンとの違いが、
全然はっきりしないんですよね。

具体的には、ウォールに入る前に一回別マップをまたぐと大丈夫だったり、
あるいは、map071でウォールに入る際のポジションが(x7,y2)以外だとOKだとか、
またあるいは、デバッグファイルのend以下をデリートすると大丈夫とか、
(end以下はそもそも読んでないだろと。。）もう何のこっちゃ？って感じです。

うーん、何か単純ミスをしている可能性もありそうですが、
不思議です。原因分かりますでしょうか？

**Comment by beta1139** [comment]
メモリ破壊してんのかもしれんな
完全に再現できる手順を知りたい

**Comment by beta1139** [comment]
とりあえず、スクリプト読み込み処理時にログを追加して、別途、./debuglogフォルダの下に出力するようにしました。
ちょっと処理が重くなるので、デフォルトでは機能をオフにしてます。
config_CS.exeで出力のオンオフを切り替えられるようにしましたので、DebugLog出力onにして、
現象を再現して頂いて、ログをアップしてもらえますか

**Comment by i7-FF7FC** [comment]
すみません。。。何故か再現しなくなりました。。orz
変わったと言えば、あれからPCをシャットダウンしたぐらいなので、
何かこちらの環境が当時不安定だったのかも知れません。
(そもそも自分の環境しか再現されなかったみたいですね。。)
折角骨を折って頂いたのに、本当に申し訳ありません。
私自信ワクワクしながら強制終了を出しに行ったのですが。。

この間、特にPC環境をいじったりしたわけではないので、
ひょっとしたらまた何かのタイミングで発生するかも知れません。
その時は改めて、今回の機能を活用させていただきます。
ありがとうございました、そして重ねて申し訳ないです。

**Comment by beta1139** [comment]
いやそれがメモリ破壊のいやらしさやねん
バグってないとはまだ確証は持てない

**Comment by i7-FF7FC** [comment]
closeしてもまだ書けるんですね、良かった。
嬉しい・・・！のかどうか分かりませんが再現しました。
デバッグログ(４つとも再現時のログ)ほか、一応再現時の差分ファイルも
同梱しときましたんでご確認ください。お願いします。
http://ux.getuploader.com/FF7FC_up/download/50/trunk.zip

ちなみに現在、デバッグファイルからmap071→072→079と移動して、
079と072を行ったり来たりしてるとエラーが出ます。

**Comment by beta1139** [comment]
ああ、最下行にincludeがある場合の処理がミスってるのかもしれないなー

**Comment by i7-FF7FC** [comment]
ああーそれっぽいですね
それだとウォールを弄ってから急に落ちるようになったのも辻褄合いますし、
さっきもまた違うシーン弄ってて落ちたんですけど(これは通常のエラーの方)、
その時のスクリプトも同じように最下行がincludeで終わってたんですよ。
ちなみに、dbg.txt見たら「slide_npc 7296L｣Maz7」と、これまで見たことない記述。
んでinclude下に適当なスリープ値打ったら発生しなくなりました。

**Comment by beta1139** [comment]
修正完了。
報告＆確認ありがとうございました。
