### ISSUE TITLE
キャラとnpcの移動速度が共にslowの場合に・・・

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#22]
キャラを動かしつつnpcも動かした場合、
移動中npcだけ画像が暈けてしまうのですが、何とか改善できないでしょうか？

例えば、「ichibangai_station_baret.txt」に↓
wait_same_pos
chg_event_move_char_speed slow
chg_speed 108 slow
move_char right 8
move_npc 108 right 8
sleep 256
move_char up 8
move_npc 108 up 8
sleep 256

**Comment by beta1139** [comment]
修正しました。
move_char right 8 のときにキャラが上下に揺れてなかったのでそれも修正しました。

**Comment by i7-FF7FC** [comment]
キャラ、npc共にslowでup移動時に、再びnpcが暈けるのを確認しています。
この症状は、歩行アニメ2回に変える前からあったので、
おそらくその前、チョコボ騎乗あたりを弄ってた時からかもしれません。

**Comment by beta1139** [comment]
修正完

**Comment by i7-FF7FC** [comment]
createしたnpc_eventより大きいIDのevent_generatorで、
キャラ、npc共にslowで動かすと、npcの画像が暈けるようです。
sleep 1やID調整で解決するので、バグというより、
ひょっとしたら例の仕様による範疇かも知れませんが、
normal以上だと発生しないので、お尋ねします。

「参考スクリプト」
wait_same_pos
create npc_event 90098 900 8 13 1 0 0 none
create event_generator 90099 900 8 14 17 0 0 @aaa.txt
warp_ff3_2 900 8 14 2 up
end

「aaa.txt」
wait_same_pos
chg_event_move_char_speed slow
chg_speed 90098 slow
loop_inf
wait_key_push_edge a
move_char up 3
move_npc 90098 up 3
sleep 96
wait_key_push_edge a
move_char down 3
move_npc 90098 down 3
sleep 96
wait_key_push_edge a
move_char right 3
move_npc 90098 right 3
sleep 96
wait_key_push_edge a
move_char left 3
move_npc 90098 left 3
sleep 96
pool

**Comment by beta1139** [comment]
色々いじってるうちに、SLOW時にキャラが動くタイミングとＮＰＣが動くタイミングが一致しなくなってました。
event_generatorが命令発行後、キャラが奇数フレーム時、ＮＰＣが偶数フレーム時に動くようになってました。
event_generatorが命令発行後、どっちも偶数フレーム時に動くように修正しました。

**Comment by i7-FF7FC** [comment]
確認しました！
どうもありがとうございます。

**Comment by i7-FF7FC** [comment]
再び問題を確認しました。
今度は逆に、npc_eventより小さいevent_generatorで、
キャラ、npc同時にslowで動かすと、npcの画像が暈けるようです。
・・・しかしこのイシューは、一体いつ本当のcloseになるのだろうか笑

wait_same_pos
chg_speed 108 slow
chg_event_move_char_speed slow
loop_inf
wait_key_push_edge a
move_char up 4
move_npc 108 up 4
sleep 128
wait_key_push_edge a
move_char down 4
move_npc 108 down 4
sleep 128
wait_key_push_edge a
move_char right 4
move_npc 108 right 4
sleep 128
wait_key_push_edge a
move_char left 4
move_npc 108 left 4
sleep 128
pool

**Comment by beta1139** [comment]
(Ａボタンを押したフレーム）
↓　
キャラの処理実行
↓
event_generatorの処理実行
move_char up 4 でキャラを移動状態にする
move_npc 108 up 4 でnpcを移動状態にする
↓
108番のnpcが移動処理開始（1フレーム目）（移動速度がslowなのでこのフレームでは移動しない）
↓
（次フレーム)
↓
キャラが移動処理開始（1フレーム目）（移動速度がslowなのでこのフレームでは移動しない）
↓
event_generatorはsleep 128
↓
108番のnpcが移動処理開始(2フレーム目)（移動速度がslowなのでこのフレームでは移動する)
↓
（次フレーム）
↓
（続く）

となってまして、
移動速度がslowの時は移動開始後偶数フレームのときに1ドット移動処理させてまして、
この場合は、キャラが移動するフレームとnpcが移動するフレームが交互に実行されているため
表示がバグってます。
なので、event_generatorのIDを大きい数字にして実行するというルールにしましょう。。

**Comment by i7-FF7FC** [comment]
あーこれこそ例の仕様でしたね。
分かりました。これまで打ったスクリプトはsleep1で対処することにします。
