### ISSUE TITLE
キャラチップのデフォ

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#23]
以前キャラチップの揺れが実装された時に、キャラチップのデフォルトの位置
(down・upが右側みたいな)を修正してもらったことがあったので、再度お願いするのは恐縮なのですが、
改めて、up/down/left/right、全てキャラチップの「左側」をデフォにすることできませんか？
よくよく考えると、そっちの方が作成時に分かりやすいなと。。
(character.bmp自体のコンバートは簡単に出来ますし)
もちろん急ぎでも何でもないので、余裕のある時で全然結構です。

**Comment by beta1139** [comment]
down・upも左側に修正しました。

**Comment by i7-FF7FC** [comment]
ありがとうございました。character.bmp修正しました。

で、関連バグだと思うので、このまま続けたいと思います。
npcをevent.csvで等を読み込む時は問題ありませんが、
create～でやった場合、以下の問題を確認しています。

・npc(2と3含む)を生成した場合、up/downのデフォ位置が右になっている
・npc_eventを生成した場合、not_moveだと問題なし、
　not_stepでデフォ位置が逆、
　normal、fast、slowだとデフォ位置が右の状態で、ちょっとしたタイムラグがあった後、
　左に戻るようになっている

**Comment by beta1139** [comment]
すいません。
修正してみましたが、どうでしょうか。

**Comment by i7-FF7FC** [comment]
okです、お疲れさまでした！
