### ISSUE TITLE
翻訳依頼

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#24]
「エルミナ回想」～「ワイヤー登り」のイベント作成しました
対象ファイルは以下の通りです。お願いします。

event_e.csv/
common\act\act1-7_2e.txt/
058\goban_slums_small_talk1.txt/
060/061/
063\goban_slums_child.txt/
064/066/067/
072\wm_barker.txt/
075\wm_boutique5.txt/
079\porch_honey_bee_inn3.txt/
084/
086\zinc_battery.txt/
088/089/
092\kotch_escape.txt

**Comment by ff7fc-translate** [comment]
できました～。
一応コミットあるたびに前回からの差分とか日本語との差分とかチェックしながら
翻訳してるので、わざわざリストアップしてくれなくても大丈夫ですよ。
