### ISSUE TITLE
slideとmoveで移動するnpc間に生じる隙間

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#26]
npcを上下に並べて、それぞれslide(walk)とmoveで移動させて分かったのですが、
移動中周期的に、各々のnpc間で1pxの隙間が発生していました。

下に参考スクリプト書いときます。
(ちょっと分かりにくいかもしれないので、再生スピード：最遅推奨です。
あとツイッタで参考画像上げときました)
https://twitter.com/i7ff7

ちなみに、npcの速度がnormal以上だと、この隙間は発生しないのですが、
slowの場合で発生するようです。
まぁ通常のnpcだと、移動中この程度の隙間があっても別に気にならないのですが、
チョコボに騎乗したnpcみたいな、2チップで一つの画像を構成してるタイプだと、
隙間が出来ると一瞬首が切れたみたいになるんですよね・笑

warp_ff3_2 900 10 10 2 up
draw_char off
create npc_event 90098 900 10 10 0 2 1 none
create npc_event 90099 900 10 11 0 1 1 none
slide_walk_npc 90098 down 4
move_npc 90099 down 4
sleep 128

あと、npcだけかなと思ってキャラも調べてみたんですが、
これはまた複雑で、キャラの場合は、移動速度がnormalだろうとfastだろうと、
npcとの間に1pxの隙間が生じていました。特にfastでは2pxの隙間でした。
あと、npc同士の場合と違って、移動中常に隙間が発生しているのも異なる点でした。

warp_ff3_2 900 10 10 2 down
chg_event_move_char_speed fast
set_slide_walk_char_flag
move_char down 8
create npc_event 90099 900 10 11 0 1 3 none
move_npc 90099 down 8
sleep 64

**Comment by beta1139** [comment]
npcを上下に並べて移動させたときに隙間ができるバグは普通にミスってました。

キャラとnpcを上下に並べたときに隙間ができるバグですが、
プログラムの作りとして、イベントＩＤの小さい順に全てのイベントオブジェクトを実行しておりまして、
event_generatorが提示のスクリプトを実行すると、
move_char down 8　でキャラがmove状態に遷移。移動処理自体はまだ実行してない
create npc_event 90099 900 10 11 0 1 3 noneでnpc生成
その後、スクリプトを実行しているevent_generatorがsleepに入った後、
同一フレーム内の処理で、生成した90099番の処理が実行されて、npcが移動処理実行する。
(event_generatorのイベントID:107よりも90099の方が大きい数字なので、
 event_generatorの処理後に90099番の処理が実行される）

となっておりまして、キャラが動き出す前に1フレーム分早くnpcが動作するようになってました。
なので、move_char down 8 を実行した際に、move状態に遷移させるとともに移動処理も
1回実行するように修正しときました。

これで一応提示されたスクリプトではうまく動作することが確認できましたが、
スクリプトを実行しているevent_generatorのイベントＩＤが、createで生成するnpcのイベントＩＤよりも
大きい数字の場合、npcの最初の実行が次フレームとなってしまいまして、
今度は逆にキャラの方が1フレーム分早く動作してしまいますので、
スクリプトを実行するevent_generatorのイベントＩＤは、createで生成するnpcのイベントＩＤよりも小さい数字
で指定するというルールにしときますかね

**Comment by i7-FF7FC** [comment]
ありがとうございました！
これは修正がちょっと面倒くさいかもと思ってたので、
こんなに早く修正してもらってビックリでした。

なるほど、、となると、これまでevent_generatorで打ってる
high IDのイベントファイルが気になるところではあります。
何となく自分の中でcreateするnpc_eventはxx20以降、みたいな変なルールが醸成されてたんですよねｗ
20って結構若いからなぁ・・・大丈夫だろうか・・・まぁ仮に問題があっても、
表示が一瞬ずれるぐらいだから、対した問題ではないのかな・・・？ですよね？
これからはxx80ぐらいから始めるかなぁ
