### ISSUE TITLE
npc移動モーションのup

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#27]
npcのup時に、左に-1pxずれる際(1～8フレーム)ですが
画像が変わってないみたいです。
正確には9～16フレでずれていない時に、画像が変わって、要するにアベコベになってるようです。
因みにキャラは大丈夫です。
何か変だと思っていたけどようやく分かった。。

**Comment by i7-FF7FC** [comment]
追記
フレーム数はnormal時のものです。

あとそれに関連したissueがあったので、ついでに書いときます。
改めてff3の移動モーションを調べたところ、
通常ff3のnpcは、キャラの半分のスピード(slow)で移動しているため、
移動モーションが、キャラとはまた違ってました。

具体的には、16ドット進むのに、「左1px及びサイド画像」に切り替わるフレームが2回登場。
要するに、スピードが1/2になっても、切り替わるスパンはノーマル時と同じになってて、
1～8フレームを通常画像とした場合、、9フレームで切り替わり、その後17フレームで元に戻る、
そして25フレーム～32フレームで再び切り替わっている模様。

そんなわけで、FF7FCの移動モーションも、
slow時は、2回切り替わる仕様が望ましいかも知れません

**Comment by beta1139** [comment]
>npcのup時に、左に-1pxずれる際(1～8フレーム)ですが
>画像が変わってないみたいです。
ん～。これってcharacter.bmpの画像の配置を変えることでは解決できない？
ちなみにバレットのupの画像って左側が右手が後ろの画像になってて、右側が左手が後ろの画像になってて、
クラウドと逆なんすよね～。

**Comment by i7-FF7FC** [comment]
ごめんなさい、ちょっとよく分からないんですが、
character.bmpって、左側がデフォで、ずれる時の画像が右側ですよね？
配置を逆にしても、ずれる時に画像が左(デフォ)で、
ずれていない時に画像が右になる現象は変わらないと思うんですが、
・・・アレ？俺が何か勘違いしてる？

たぶん再生スピード最遅で、キャラのup時と比較して頂ければ分かると思いますが、
キャラの場合は、普通にずれるタイミング(1～8フレーム)で画像が右側に変わっているのに対して、
npcのupは、1～8フレームでは、画像は1pxずれているものの、画像はそのまま左側なんですよね。

あっ、ちなみにバレット、クラウドと逆にしてるのワザとなんです。
バレットは右腕の銃が特徴なので、それを少しでもドットで分かるように、銃が目立つ方をデフォにしてます。
ff3で確認したところ、up/down時のデフォ(右足が前とか)って結構バラバラだったんですよねw

**Comment by i7-FF7FC** [comment]
一応確認スクリプト書いときます

■charの場合

warp_ff3_2 900 10 10 2 down
loop_inf
wait_key_push a
move_char down 4
sleep 64
chg_char_dir up
wait_key_push a
move_char up 4
sleep 64
chg_char_dir down
pool


■npcの場合

warp_ff3_2 900 10 10 2 down
draw_char off
create npc_event 90099 900 10 11 0 1 2 none
loop_inf
wait_key_push a
move_npc 90099 down 4
sleep 64
chg_npc_dir 90099 up
wait_key_push a
move_npc 90099 up 4
sleep 64
chg_npc_dir 90099 down
pool

**Comment by beta1139** [comment]
ああ～。意味分かりました。
npcの処理はどの方向に移動してるときも0~8フレームが左側画像になってました。
upとleftは0~8フレームが右側画像、それ以降は左側画像を表示するよう修正しました。

**Comment by i7-FF7FC** [comment]
あっ、分かってもらえて良かった。
てかleftは気付いてなかったｗ、あんだけ詰めてて分からんもんかと己に凹む春の午後orz

あとslow時の処理(2回切り替わる仕様)は、余裕がある時でもご検討ください～
別にバグでも何でもないので

**Comment by i7-FF7FC** [comment]
すいませーん、またまたトラブル発生ですｗ
npcのup/leftの画像切り替えのフレームが変わったことによって、
チョコボ騎乗のnpcがslide(walk)で移動したときに、再び画像が崩れるようになりましたw
なので、slide(walk)時は、従来どおり、「どの方向に移動してるときも0~8フレームが左側画像」
になるよう再調整していただけませんか？

wait_same_pos
kill_through 108
draw_char off
create npc_event 198 1 2 10 137 0 1 none
create npc_event 199 1 2 11 137 3 1 none
loop_inf
wait_key_push a
slide_walk_npc 198 right 2
slide_walk_npc 199 right 2
sleep 64
wait_key_push a
slide_walk_npc 198 left 2
slide_walk_npc 199 left 2
sleep 64
pool

**Comment by beta1139** [comment]
修正しました

**Comment by beta1139** [comment]
slow時に移動アニメを2回入れる処理入れました
