### ISSUE TITLE
宝箱を開けた時のメッセージ

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#28]
現在、宝箱やアイテムを見つけた時は、
すべて「こんなところに　xxが！」というテキストになっていますが、
ff3では宝箱の場合、

　たからばこのなかには
　　xxがはいっていた！

となっている模様です。
気が向いた時にでもご検討くださいー

一応参考画像
https://twitter.com/i7ff7/status/600652535335104512

**Comment by beta1139** [comment]
修正しました。宝箱の表示位置を４ドットずらさない修正もしました。
