### ISSUE TITLE
Map Editorでアタリ判定無視

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#29]
Map Editorでの作業ですが、一時的にアタリ判定を無視して歩けるようになりませんか？
アタリ判定を入れると自由に移動できなくなるので、なるべく最後の方に入れるようにしてるんですが、
どうしても入れた後デバッグしながら再調整することも多いので、
何か適当なショートカットキー押したら(あるいは押しつつ移動したら)無視できるとか、
出来たら便利だなと以前より思っていたので、一度リクエストしときますー。

**Comment by beta1139** [comment]
シフトキー押下で当たり判定有効／無効を切り替えられるようにしました（マップエディタ、ゲーム本体両方対応）
