### ISSUE TITLE
提案（要望：優先度低）どこでもセーブ／ロード機能

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#3]
デバッグ用にキーボードショートカットでどこでもセーブ／ロード的な機能があるとうれしいです。
会話の選択肢でそれぞれの選択の結果を確認したいような時など。
オンメモリで１件のみセーブ可能、とかでも良いかと思います。

**Comment by beta1139** [comment]
エミュレーターとかによくついてる機能ですよね
う～む、どうしたらいいんだろうなー

**Comment by ff7fc-translate** [comment]
実装がそれほど簡単じゃなさそうな上に、
いろいろ代替策はありそうなのでクローズします。
