### ISSUE TITLE
宝箱ga

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#31]
warp 103 10 19 down
で宝箱が取れなくなりました。

**Comment by i7-FF7FC** [comment]
途中で送信してしまった。。
タイトル変更したり、もしくは削除するのって出来ます？

一応追記
宝箱とキャラが両方上層の場合、キャラが宝箱の下に隠れるバグも確認しています。

**Comment by ff7fc-translate** [comment]
右上の「Edit」（「New Issue」の左隣）ボタンでタイトル編集できますよ。
あと各コメントの右上のペンマークでコメント編集、各コメント右上のバッテンでコメント削除です。

**Comment by beta1139** [comment]
たぶん、修正しました。。

**Comment by i7-FF7FC** [comment]
どうもタイトル編集できました、
修正もお疲れ様でしたー
