### ISSUE TITLE
Active FlagがOffで無音指定のMAPに入った場合

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#34]
非アクティブからアクティブ状態に復帰すると、
一つ前に鳴らしていたbgmが再生される模様です。

**Comment by i7-FF7FC** [comment]
追記
上の状態になってから、さらにbgmが指定してある別マップに飛ぶと、
今度は移動先のマップBGMと、これまで鳴っていたbgmの両方が再生されます。

**Comment by beta1139** [comment]
すいません。再現するスクリプトを貰えませんか。

**Comment by i7-FF7FC** [comment]
Config_CS.exeよりActive Flagをoffにして、例えば以下のようなスクリプトを打って、
無音のマップに移動します↓

warp_ff3_2 11 1 1 2 up
create event_generator 1199 11 1 2 17 1 0 @aaa.txt
set_flag 0 0
end

[aaa.txt]
wait_same_pos
warp_ff3_2 900 1 1 2 up

移動した時点では無音だと思いますが、
次に画面からフォーカスをはずして、再度フォーカスを当てると、
無音だったマップからBGM(爆破ミッション)が流れ始めます。

さらに、一歩下の「aaa.txt」を踏んで別マップに移動すると、
爆破ミッションのBGMが流れたまま、移動先のマップ(900)BGMも流れます。

**Comment by beta1139** [comment]
修正しました。
nothing、through指定のマップにワープした際にサウンドハンドルを保持してませんでした。
