### ISSUE TITLE
add_itemでキーアイテムを指定した際の原因不明のエラー

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#37]
何故かadd_itemでキーアイテムを指定すると、
キーアイテムの中が空になり、キーアイテムの欄で決定ボタンを押すと落ちるようになりました。
下記がエラーメッセージです。原因分かりますでしょうか？

[dbg] func_name:PartyMember::get_item_data, line:701 >>> item not found. (item_type:5, item_pos:1919049312)

不思議なのが、「warp6.txt」で、「set01.txt」より
同様にスクリプトでキーアイテム追加してるんだけど、
これは何の問題も無くキーアイテム追加されてるんですよねｗ
しかし、set01.txtをいじって、一つでもキーアイテムを変更すると、上記のような状態になる。。
何だこれは・・・ｗ

**Comment by beta1139** [comment]
メニュー画面のキーアイテム表示の際に使用するスクロール位置に関する変数を初期化してませんでした。
