### ISSUE TITLE
set_flag 0 5→set_flag 0 0後のBGM再生の不具合

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#38]
set_flag 0 5→set_flag 0 0にした直後は問題ないのですが、
その後set_flag 0 0のまま、別マップに移動すると、
移動先のBGMを既に鳴らしていた場合、途中から再生される模様です。
おそらくこの説明では分かりづらいと思うので↓を参照ください

wait_same_pos
set_flag 0 0
warp_ff3_2 72 0 0 2 down
msg 　げんざい　『set flag 0 0』で\n　MAP72のBGMがさいせい\n　msgをとじると　『set flag 0 5』に\n　きりかわり　テキトーなマップへ
loop_inf
set_flag 0 5
warp_ff3_2 5 0 0 2 down
msg 　げんざい　『set flag 0 5』で\n　BGMさいせい\n　msgをとじると　『set flag 0 0』に\n　もどり　べつのマップへ
set_flag 0 0
warp_ff3_2 13 0 0 2 down
msg 　げんざい　『set flag 0 0』で\n　MAP13のBGMさいせい\n　msgをとじると　『set flag 0 0』\n　のまま　さいしょのMAP72にもどる
warp_ff3_2 72 0 0 2 down
msg 　げんざい　『set flag 0 0』\n　MAP72のbgmがとちゅうから　さいせい
pool

**Comment by beta1139** [comment]
修正しました。
