### ISSUE TITLE
提案（要望：優先度低）スクリプト内の全角／半角文字マッピング

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#4]
イベントスクリプト内のメッセージ記述で、英数と大部分の記号については全角／半角
どちらでも使えるようになっていますが、一部の記号は全角でしか記述できません。
現在全角が必要なのは『』「…→▼（ハート）の６文字かな？
これらを現在使われていないASCII文字に割り当てて英語版スクリプトは半角のみで
記述できるようになるとうれしいです。
たとえば『 』「…→▼ をそれぞれ { } ` = > @ に割り当てるとか。

**Comment by beta1139** [comment]
『』「…→▼　を　{}`=>@　でも指定できるように修正しました
