### ISSUE TITLE
グレイスケールの調整

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#41]
以前グレイスケールの提案をした時に、
FF3は、エンカ時にモノクロ処理が走っていると書きましたが、
改めて調べてみると、どうも単純にモノクロになってたわけじゃないみたいですね。

大雑把に書くと、パレットの暗色をRGB値で127/127/127、
中間色を188/188/188、明色を255/255/255の3色に変換してるっぽいです。

で、パレットチェンジを使わずに、
大体コレと似た感触を得られないかと調整してみたところ、
screen_effect addを使って、今のグレイスケールに白を30%前後足すと、
体感的には割と近い感じになりました。(下記スクリプト参照)
そこでグレイスケールのデフォを、このぐらいの濃度にできないでしょうか？

※スクリプトの実行前に、予め↓の「ff3.bmp」と「ff3_gray.bmp」を、
imageフォルダに突っ込んでおいてください。
http://ux.getuploader.com/FF7FC_up/download/53/ff3_reference.zip

[参照スクリプト]
wait_same_pos
draw_image 000 0 8 0 0 256 224 1 ff3.bmp
draw_image 001 0 8 0 0 256 224 1 ff3_gray.bmp
set_image_alpha 001 0
loop_inf
msg 　msgをとじると FF3の　エンカエフェクト\n　1フレームごとに　パレットチェンジとリセットを\n　32かい　くりかえす(けい64フレーム)
play_se encount.ogg
loop 32
set_image_alpha 001 100
sleep 1
set_image_alpha 001 0
sleep 1
pool
msg 　msgをとじると ていあんする　エンカエフェクト\n　じゅうらいの　グレイスケールに　しろをプラス
play_se encount.ogg
loop 32
set_screen_effect add 255 255 255 29
set_gray_scale
sleep 1
reset_screen_effect
reset_gray_scale
sleep 1
pool
msg 　msgをとじると　じゅうらいの　エンカエフェクト
play_se encount.ogg
loop 32
set_gray_scale
sleep 1
reset_gray_scale
sleep 1
pool
pool

ただエルミナの回想シーンに関しては、
今ぐらいの濃度でちょうどいい(あんま明るくすると文字が見づらくなる)ので、
従来の濃度を「gray scale2」として残し使い分けるか、
あるいは、同梱ファイルのような「セピア色」がもし可能なら、
新規にエフェクトを追加して頂けたら嬉しいです。

**Comment by beta1139** [comment]
エンカウント時のグレイスケール画像に３０％程白成分を加えました
ちなみにエンカウント時のエフェクト処理と、set_gray_scale使用時のエフェクト処理はもともと別処理になってます。

**Comment by i7-FF7FC** [comment]
ありがとうございます！
