### ISSUE TITLE
掌打ラッシュ時の応答停止

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#44]
以前から、ティファの掌打ラッシュを打つ際に、稀にフリーズすることがあって
ちょっと保留にしといたんですが、ようやく原因が分かりました。
どうも同じ戦闘中に2回打つと発生するみたいです。
2回目の掌打ラッシュのスロット選択後に画面が固まりexeが応答を停止します。

**Comment by beta1139** [comment]
う～ん、どうも再現しないっす

**Comment by beta1139** [comment]
しょうだラッシュとは関係ないんですがフリーズしました。
私の場合はバレットとクラウドの二人パーティのときに、
バレットが死んでいる状態でクラウドのコマンド入力後にフリーズしました。
しかしタイミングか何かの要因があるようで再現はしませんでした。
もしテストプレイ中にフリーズして、再現方法が分かった方がいましたら報告お願いします。

**Comment by beta1139** [comment]
再現し、修正しました
攻撃のターゲットの敵のidが 0 ~ 2 の乱数から選択するように実装されてました
0 ~ 2 の敵が既に全員死んでいると無限に乱数を取得し続けフリーズ
