### ISSUE TITLE
set_image_trans_colが効かない

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#46]
set_image_trans_colですが、どうも初回のdraw_image時には効かないようです。
2回目のdraw_image以降は効きます。
と言うより、2回目以降は何も打たなくても、前回打ったset_image_trans_colが維持されているので、
誤作動を避ける為、透過色のリセット命令(透過しない)もあると嬉しいです。

wait_same_pos
draw_image 000 0 0 0 0 256 240 0 title.bmp
set_image_trans_col 000 40 0 184
msg げんざい　ブルーバックのいろ\n　[40 0 184]　をとうめいせってい\n　1かいめは　きいていない
erase_image 000
sleep 16
draw_image 000 0 0 0 0 256 240 0 title.bmp
msg げんざい　ブルーバックのいろ\n　[40 0 184]　をとうめいせってい\n　2かいめは　きいている

**Comment by i7-FF7FC** [comment]
追記
よく考えたら、リセット命令は使わない色を指定すればいいだけなので、結構です、すいませんｍ(_ _)

**Comment by beta1139** [comment]
set_image_trans_col命令はまだ一箇所も使われてないようなので仕様変更します。

画像IDは無しにして、
set_image_trans_col (r) (g) (b)
とし、draw_image実行前に設定して下さい。
