### ISSUE TITLE
全滅後コンティニューでバグる

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#47]
戦闘で全滅してニューゲームからコンティニューすると、
最初のバレットのmsg「いくぞ～」の前に、「タルがある～」(スラム教会イベの台詞)の
msgが表示されて、その後落ちたり色々バグります。

**Comment by beta1139** [comment]
う～ん、再現しませんでした。。

**Comment by beta1139** [comment]
開始後すぐにワールドマップに飛んで全滅したら再現しました！
初期化漏れを発見したので修正して改善されたことを確認しました。
