### ISSUE TITLE
マップエディタで下の枠外に打った際に発生する現象

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#48]
以前マップエディタで右の枠外（X印のとこ）に、はみ出して打つと、
下に表示されるバグがありましたが、同様に下の枠外に
はみ出して打つと、今度は一番上周辺のチップが消えます。
たぶん隅々まで敷き詰めてるmap20で試すと分かりやすいと思います。

**Comment by beta1139** [comment]
修正完
