### ISSUE TITLE
提案（要望：優先度低）バックグラウンド実行

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#5]
ウィンドウからフォーカスを外した状態でも実行を継続させられる
オプションがあるとうれしいです。
時間制限イベントの時間切れを起こしたい場合など、
同じPC上で他の作業をしながら時間切れを待てるとうれしい。

**Comment by beta1139** [comment]
Config_CS.exeツールで非アクティブ時も動作させるかどうか設定できるようにしときました
