### ISSUE TITLE
平仮名をつかった場合の選択肢の不具合

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#50]
以下のような選択肢で、「ウォールマーケットへ」を選択しても、
その後の「いりぐち～」等の分岐に行きません。

create npc 163 1 4 12 64 0 0 デバッグよう　ワープそうち\n「クエッ！\n\n\n#4\n　　らせんトンネルへ\n　　スラムきょうかいへ\n　　ウォールマーケットへ\n　　きょうみないね\n[[]][[#4\n　　シーン1\n　　シーン2\n　　シーン3\n　　シーン4\n[[]][[]][[]][[]]]][[#4\n　　いりぐち\n　　ドレスにゅうしゅご\n　　カツラにゅうしゅご\n　　きょうみないね\n[[]][[]][[]][[「あ　そ！]]]][[「あ　そ！]]

これを↓数字に置き変えればちゃんと機能するので、おそらくそれ関係の不具合が生じてるかと。
create npc 163 1 4 12 64 0 0 デバッグよう　ワープそうち\n「クエッ！\n\n\n#4\n　　1\n　　2\n　　3\n　　4\n[[]][[#4\n　　2-1\n　　2-2\n　　2-3\n　　2-4\n[[]][[]][[]][[]]]][[#4\n　　3-1\n　　3-2\n　　3-3\n　　3-4\n[[]][[]][[]][[「あ　そ！]]]][[「あ　そ！]]

**Comment by i7-FF7FC** [comment]
追記
というか、event,csvに記述している選択肢もおかしなことになってますね。。
2番目がちゃんと機能しなくなってて、場合によっては落ちます。。

例えばnpc2401の「むすこは　もう　たびだちましたかな？～」
の選択肢の2番目を選ぶと、セリフがバグります。

他、以下のnpcをcsvより新規に設置したところ、選択肢の2番目を選ぶと落ちました。
[dbg] func_name:Graphics::draw_text, line:870 >>> 刀

「スクリプト」
npc,12000,120,29,11,73,1,2,"「なんだおまえは？
　こんなところで　なにをしている？


#2
　　エアリスはどこだ！
　　…………


[[「エアリス？
　そのなをしっているとは
　おまえまさか！？

　エアリスってあのコだろ
　うけつけの
　じつはオレも　あのコ
　きになってるんだよね
　ウーン　はやくも
　ライバルしゅつげん……


　え　そうじゃない？
　なんだ　ひとちがいか]]
[[　ハハーン……わかったぞ
　さてはおまえ　アレだな？
　いまウワサの……

　しんらカンパニー　しゅうりか！！



　いや～　このビルも
　そろそろあちこちに
　ガタがきててなあ

　このかいのドア
　ひらきっぱなしなんだ
　はやく　なおしてくれよな

　あ　そうそう
　いちおう　ほかのかいも
　みまわってくれよ
　これ　やるから]]"

**Comment by beta1139** [comment]
修正しました。
"シーン"の'ー'の2バイト目と'['の文字コードが同じためおかしくなってました。
以前は'['と'['の2バイトで判定してたんですが、この前の選択肢を増やす修正で
'['の1バイトのみで判定するように処理を変更してしまってて不具合に繋がってました。
’ー’以外にも'['と同じ文字コードが全角文字の中に含まれていた場合は全て不具合になってました。

**Comment by i7-FF7FC** [comment]
ありがとうございました。
それで、またちょっと選択肢を増やしてやってたら落ちました笑
"ー"を削ったらokだったので原因たぶん一緒だと思いますが、
下記の「スラムきょうかいへ」→「きょうみないね」で「あっそ」が出ません。
「スラムきょうかいへ」→「シーン1」等で落ちます。

create npc 163 1 4 12 64 0 0 デバッグよう　ワープそうち\n「クエッ！\n\n\n#4\n　　らせんトンネルへ\n　　スラムきょうかいへ\n　　ウォールマーケットへ\n　　きょうみないね\n[[]][[#5\n　　シーン1\n　　シーン2\n　　シーン3\n　　シーン4\n　　きょうみないね\n[[]][[]][[]][[]][[「あ　そ！]]]][[#5\n　　いりぐち\n　　ドレスにゅうしゅご\n　　カツラにゅうしゅご\n　　じょそうご\n　　きょうみないね\n[[]][[]][[]][[]][[「あ　そ！]]]][[「あ　そ！]]

**Comment by beta1139** [comment]
選択肢5個以上の場合の処理が別処理になっててそっちが修正漏れでした。
