### ISSUE TITLE
選択肢処理の不具合

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#52]
再び選択肢の不具合ですが、今回のは、
選択肢を数字に置き換えても解決しませんでしたので、違うissueとして上げます。

下記スクリプトの選択肢で「もうおしえることはない」以外を選んだ場合に、
最初の「10みまん1」は表示されるのですが、最後の「10みまん2」の表示が出ません。
因みに、一番最後の「if_flag_lesser 3 10～fi」を外すと上手くいくので、バグかなと思った次第です。

「ichibangai_station_baret.txt」
wait_same_pos
warp_ff3_2 900 237 127 2 up
create npc2 90098 900 237 126 66 1 0 
create event_generator 90099 900 0 0 17 1 0 @001/test.txt
end

「test.txt」
set_eternal_event
wait_target_talk 90098
reset_talk_flag 90098
msg 『なにが　しりたいんだ？\n\n\n\n#11\n　　きろくを　のこすには？\n　　みかたを　かいふくするには？\n　　まほうをつかった　かいふく\n　　ぶき　ぼうぐの　つかいかた\n　　マテリアの　そうちゃく\n　　マテリアの　こうどなつかいかた\n　　せんとうじの　たいけいについて\n　　じぶんのじょうたいを　チェック\n　　リミットわざの　つかいかた\n　　そのほかの　だいじな　ちゅういじこう\n　　もうおしえることはない\n[[]][[]][[]][[]][[]][[]][[]][[]][[]][[]][[]]
if_flag_lesser 3 10
msg 10みまん1
fi
if_flag 3 0
msg 『きろくのとりかた（セーブ）を　せつめいする
fi
if_flag 3 1
msg 『HPは　せいめいりょく\n　MPは　まほうの　もととなる　ちからだ
fi
if_flag 3 2
msg 『（まほうをつかった　かいふく）\n　Not Found
fi
if_flag 3 3
msg 『（ぶき　ぼうぐの　つかいかた）\n　Not Found
fi
if_flag 3 4
msg 『（マテリアの　そうちゃく）\n　Not Found
fi
if_flag 3 5
msg 『（マテリアの　こうどなつかいかた）\n　Not Found
fi
if_flag 3 6
msg 『（せんとうじの　たいけいについて）\n　Not Found
fi
if_flag 3 7
msg 『（じぶんのじょうたいを　チェック）\n　Not Found
fi
if_flag 3 8
msg 『（リミットわざの　つかいかた）\n　Not Found
fi
if_flag 3 9
msg 『だいじなことがある！
fi
if_flag 3 10
end
fi
if_flag_lesser 3 10
msg 10みまん2
fi

**Comment by beta1139** [comment]
なんか新しくmsgウィンドウを開くときにflagを100で初期化する処理が入ってました。
とりあえず初期化処理を消すことで正常動作確認しました。
