### ISSUE TITLE
イベントファイル不足

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#53]
以下の２ファイルが足りないようです：
common/084/plate_section1_ready.txt
common/089/plate_section1_start.txt

インクルード元：
script\001\debug_load.txt
script\084\plate_section1_common.txt
script\089\plate_section2.txt
script_e\001\debug_load.txt
script_e\084\plate_section1_common.txt
script_e\089\plate_section2.txt

**Comment by i7-FF7FC** [comment]
ご報告ありがとうございます、済みませぬ！追加しました
