### ISSUE TITLE
簡易セーブのスロット増設

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#58]
簡易セーブ＆ロードに関してですが、
スロット数を5つぐらいに増やせないでしょうか？

例えば、F2キー等で任意のスロットを選んでF5でセーブ
↓
デバッグマシンの選択肢で1～5のスロットを選んで飛ぶ
こんな感じをイメージしています

**Comment by tomo1139** [comment]
修正しました

**Comment by beta1139** [comment]
修正しました
