### ISSUE TITLE
提案（要望：優先度低）横並びメニュー項目幅

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#6]
ショップでの「かう」「うる」「でる」選択や魔法メニュー内での
「まほう」「しょうかん」「てきのわざ」選択、コンフィグメニュー
内での各種設定選択など、項目が横並びになる選択メニューで
各項目の文字数が可変にできるとうれしいです。

たとえばショップでの行動選択は
"かう□□うる□□でる□" という文字数で固定になっているが
英語モードでは "Ｂｕｙ□Ｓｅｌｌ□Ｇｏ" にしたい。

同様にコンフィグメニューの
"カーソル□□□しょき□きおく□□□□□□"
"ＡＴＢ□□□□アクティブ□ウェイト□□□"
なども
"Ｃｕｒｓｏｒ□Ｒｅｓｅｔ□Ｓａｖｅ□□□"
"ＡＴＢ□□□□Ａｃｔｉｖｅ□Ｗａｉｔ□□"
などとできたらありがたい。

**Comment by beta1139** [comment]
カーソルの移動位置まで含めて考えないといけないすね
空白の数でカーソル位置を変えるようにするかなー

**Comment by ff7fc-translate** [comment]
たとえば全てのメニュー項目の印字の起点は同じにして、
定義ファイルでは先行する空白込みで定義しておくというのもありかな？
（もちろん具体的なやりかたはお任せしますが、ひとつのアイディアとして）

日本語定義）
かう （カーソルは先頭）
□□□うる （カーソルは+3文字目）
□□□□□□でる（カーソルは+6文字目）
日本語画面表示）
かう□うる□でる

英語定義）
Buy（カーソルは先頭）
□□□□Sell（カーソルは+4文字目）
□□□□□□□□□Go（カーソルは+9文字目）
英語画面表記）
Buy□Sell□Go

**Comment by beta1139** [comment]
とりあえず、
ショップでの"Ｂｕｙ□Ｓｅｌｌ□Ｇｏ"
コンフィグメニューの
"Ｃｕｒｓｏｒ□Ｒｅｓｅｔ□Ｓａｖｅ□□□"
"ＡＴＢ□□□□Ａｃｔｉｖｅ□Ｗａｉｔ□□"
のみ、
プログラム側で固定で対応させときました。
とりあえずここの部分の処理だけなんで、データを外出しにするのもなんだかなあと思ったので。
他に変えたい部分あったら教えてください

**Comment by ff7fc-translate** [comment]
修正どうもです。
実は今までmenu.txt内でBuy/Sell/GoのGoの先頭にスペースを一個いれて
表示だけ無理やり "Ｂｕｙ□Ｓｅｌｌ□Ｇｏ" になるようにしていました
（カーソルは Ｇｏ の前のスペースを指していた）。
menu.txt内の "□Ｇｏ" を "Ｇｏ" にできるよう、テキスト描画位置も調整していただけますか？
（今は "Ｇｏ" にすると表示が "Ｂｕｙ□ＳｅｌｌＧｏ" となってカーソルが "ｏ" を指す）
コンフィグメニューはばっちりです。

**Comment by beta1139** [comment]
修正しました。
menu.txtも修正しました。
