### ISSUE TITLE
MAP Editor　チップへのジャンプ機能

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#60]
MAP Editorに関して、もう一つ要望を思い出したので、忘れないうち書いときます。
画面左の描画部分で、このマップのこのマスはどのチップを使ってたっけ？という際に、
そのマス上で例えば右ダブルクリックすると、
右画面の該当チップ部分にジャンプできるとか、そういう機能があればいいなと思ってた次第です。
俺以外の人がマップ作る時にも便利だよなと。

**Comment by beta1139** [comment]
Ｚキーで実装しました。
