### ISSUE TITLE
includeのif関連？のバグ

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#61]
下記のようなスクリプトですが、「した」を選んだ場合に落ちます。
ちなみに一度「うえ」を選ぶと、それ以降は「した」を選んでもちゃんと機能しますが、
初めに「した」を選ぶと落ちます。

「ichibangai_station_baret.txt」
set_eternal_event
wait_same_pos
msg 　バレットいどう\n\n\n\n#2\n　　うえ\n　　した\n\n\n[[]][[]]
if_flag 3 0
include ./event/script/001/test.txt

[test.txt]
move_npc 108 up 1
fi
if_flag 3 1
move_npc 108 down 1
fi
sleep 16

**Comment by beta1139** [comment]
if_flagを読み込んだ後にincludeを展開せずにfiを探して見つからずエラーとなっているようです。。

**Comment by beta1139** [comment]
修正しました

**Comment by i7-FF7FC** [comment]
お疲れ様です。修正後に新たなバグが出てきました
下記のようなスクリプトだと、本来なら
「test.txt」の内容は実行されないはずですが
testのmsgが表示されるようになりました。

「ichibangai_station_baret.txt」
wait_same_pos
if_flag 99 99
// include ./event/script/001/test.txt
fi

「test.txt」
if_party_mem 8
del_party_mem 8
fi
msg test

**Comment by beta1139** [comment]
//が考慮されてませんでした
