### ISSUE TITLE
draw_image後に全滅した場合

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#62]
全滅後に画像イレース処理を実行してもらえないでしょうか？
Gバイクイベでdraw_image実行後に戦闘に入って全滅した場合、
コンティニューすると画像が残ったままになってたので、
「erase_image_range 000 010」のような処理があればいいなと思った次第です。

**Comment by beta1139** [comment]
全滅時に erase_image_obj_range(0, 99999); 実行するようにしました
