### ISSUE TITLE
戦闘のエアリスバグ？

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#64]
エアリスをパーティに入れて、
例えばワールドマップのモンスターリストを564にして、
ある程度長時間バトルできるようにしておくと
途中(残りが1体か2体あたりが目安)からメンバーの武器のグラがバグります。
ちなみにエアリスを入れていないと、この現象は発生しませんでした。

また同戦闘において、いやしの風を打った後に
フリーズすることもしばしばありました。
dbg.txtに残らないタイプのエラーです。

**Comment by beta1139** [comment]
再現し、修正しました
