### ISSUE TITLE
バグ報告

### ISSUE THREAD

**Issue by orettioretti** [beta1139/ff7fc-develop#65]
イベント096のボス戦(アプス)が終わった後、ティファとエアリスの会話で、

ティファ

「もうダメだわ・・・・
 マリン・・・・バレット
 ・・・・スラムのひとたち

エアリス

「あきらめない　あきらめない
 はしら　こわすなんて　
そんなにかんたんじゃない　でしょ？

ティファ

「・・・・・・・・そうね・・・・そうよね！」
まだじかんはあるわよね

ここで、Aボタンを押すと、何度やっても画面が落ちてしまいます。

[dbg] func_name:Event::get_flag_talk, line:216 >>> id: 7614 not found

**Comment by tomo1139** [comment]
dbg.txtの最下行に出力されている文字列も貼り付けてもらえると助かる

**Comment by beta1139** [comment]
dbg.txtの最下行に出力されている文字列もコピペして貰えると助かります。

**Comment by i7-FF7FC** [comment]
ご報告ありがとうございます。
早速探ってみます・・・って3ヶ月も経っとるやないかーい笑
やまちゃんやめへんで

**Comment by i7-FF7FC** [comment]
修正しました。
久しぶり過ぎて覚えているか心配だったが、
備忘録のおかげで助かったナイスおれ。
