### ISSUE TITLE
if_owned_or_equipped_itemについて

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#66]
久しぶりにプレイして、ちょっと弄ってたんですが、
どうも「if_owned_or_equipped_item～」の対象IDが、
4100番以降対応していないようです。

**Comment by beta1139** [comment]
ソースコード確認してみましたが、キーアイテムのid最大値(=6999)以下であれば処理しており、
4100番のIDで条件分岐しているような箇所は見当たりませんでした。
ちょっと中身見てみないと分かりませんが最近はwindowsプログラミングはやってませんで、
専らAndroidばかりになってしまっていて開発環境も整えてないので難しいですね。。

**Comment by i7-FF7FC** [comment]
どうもお久しぶりです。
レス来ないよなぁ、、と思っていたのでビックリでしたw

時間も経って環境も変わるとやっぱり色々厳しいですよね、、
久しぶりにやってみたら面白くて、
生存報告半分で上げた部分もあるので、
期待しないで待っております。

--------------------------------------------------------------------
問題の現象に関して。
ちょっと勘違いしていたようで、
どうも4100以降ではなく、特定のIDのみ漏れてるっぽいです。

以下を「ichibangai_station_baret.txt」にコピペした場合、
デフォでは「いかずち」「れいき」のマテリアのみ所持にも関わらず、
4100と4201が「所持or装備中」判定になります。

wait_same_pos
if_owned_or_equipped_item 4100
msg ぜんたいか\n ある　or　そうびしている
fi
if_not_owned_or_equipped_item 4100
msg ぜんたいか\n  ない　or　そうびしていない
fi
if_owned_or_equipped_item 4201
msg みやぶる\n  ある　or　そうびしている
fi
if_not_owned_or_equipped_item 4201
msg みやぶる\n  ない　or　そうびしていない
fi

**Comment by beta1139** [comment]
あ、レッドXIIIの初期装備のマテリアのIDが4003, 4100, 4201になってますね。。
まだ仲間になっていない仲間が装備しているマテリアも処理対象にしてしまっているのが原因のようです。
プログラムを書き換えてアップし直さないと駄目ですね。。
最近はJava/Kotlinを使っていてC/C++も忘れてきてまして、、ちょっと厳しいですね。。

**Comment by i7-FF7FC** [comment]
なる、そういう理屈でしたか。
そっかー忘れてるかぁ、、
そりゃ期間空くとそういう部分も出てきますよね。
無理言ってスミマセン、元々駄目モトだったので全然構いません。

**Comment by J92R** [comment]
So, what happened to this project?

I've been following it for a while now and haven't seen any updates from anyone. Not even a "hey, we're still working on it and haven't abandoned it".

**Comment by beta1139** [comment]
こちら命令追加しておきました
```
if_equipped_item_for_party
if_not_equipped_item_for_party
if_owned_or_equipped_item_for_party
if_not_owned_or_equipped_item_for_party
```
アップロード済のexeとは別にff7fc_v400a.exe としてアップしておきました
