### ISSUE TITLE
マップエディタのワープ設定時の音

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#68]
さきほどSEのエラー修正してて気づいたんですが、
マップエディタのワープ入力時の音も以前のready.wavになってるようで、
いつの間にか音が鳴らなくなってるようです。(現在はready.ogg)
別に大したことではありませんが一応ご報告を。お暇な時にでもー。

**Comment by beta1139** [comment]
修正しときました
