### ISSUE TITLE
1-11-Fanfare.oggのタイミング訂正の提案

### ISSUE THREAD

**Issue by ponyexs** [beta1139/ff7fc-develop#69]
環境によるのかもしれませんが、私のところでは曲の出だしが途切れています。

このため鳴り始めのタイミングをごくわずかに遅らせて曲全体が鳴るよう調整してみました。
使い物になりそうなら採用をご検討ください。
https://drive.google.com/file/d/1MnhYrbdRpZL7FpzTdojn8paQmNzATiGH/view?usp=sharing

**Comment by beta1139** [comment]
確かに。途切れて再生されてました。
ありがとうございます！差し替えておきました

**Comment by ponyexs** [comment]
ご採用ありがとうございました！
