### ISSUE TITLE
reset_talk(ed)_flagについて

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#70]
ちょっと今更ながらの質問ですが、
「reset_talk_flag」や「reset_talked_flag」の後って、（event_id）不要でしたっけ？
今まで当たり前に打ってたんですが、ふとドキュメントのスクリプト一覧見てたら書いてなくてw

一方「950_dbg3.txt」にもevent_idがあったりで、アレどっちだ？と分からなくなった次第です。
現状打っても打たなくても落ちることはないので、どうしたらいいかなと。

**Comment by beta1139** [comment]
実装を確認してみました
idとして引数を一つ読み込んでますね
たぶんドキュメントの記載漏れだと思います
追加しておきました
