### ISSUE TITLE
新規武器追加について

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#75]
プレート崩壊イベントの時に、
ラクロナグというお遊び的な武器を仕込んでいるのですが、
こういうのって新規に追加できないでしょうか？
強さ的には、あの辺りだと神羅ビルの隠しで手に入るハードブレイカーが最強だと思うので、
比較的それに近い性能だと実用的かなぁという漠然とした考えはあるんですが。

**Comment by beta1139** [comment]
武器データは外部ファイルで管理しているようで、たぶん
`./item/weapon.txt` と `./item_e/weapon.txt` に追加すれば追加されるんじゃないかなあ
idで、装備できる人が分かれている感じ

**Comment by i7-FF7FC** [comment]
あそういう仕様でしたか！
ありがとうございます！

**Comment by beta1139** [comment]
よくできてますよねえ（自画自賛）

**Comment by i7-FF7FC** [comment]
閉じたんですが、再度質問失礼します:dash:
weapon.txtの、vit～backまでの意味が分かんないす！:sob: 
vit等は体力だと思うんですが、特に数値弄ってもステータス上は変わりませんし
throwとbackは完全に分かりませんw

**Comment by beta1139** [comment]
throw は投げられる武器のフラグぽい
back は後衛からでもダメージが変わらない武器のフラグぽい

vit等の数値は、攻撃と防御以外はまだ反映させてないぽい

**Comment by i7-FF7FC** [comment]
なるほど！ありがとうございます。
（ぽいってことは誰が作ったんだろう...:confused:）

**Comment by beta1139** [comment]
5年前の自分です。大分忘れてるので。。
