### ISSUE TITLE
コルネオの館の落とし穴にクラウドたちではなくゲーム自体が落ちる

### ISSUE THREAD

**Issue by ponyexs** [beta1139/ff7fc-develop#77]
クラウドたち3人でコルネオ恫喝後、
ティファとエアリスに衝突判定が無くなっており
2人の上を通り抜けることが可能になっています。

このときティファかエアリスの上を通り抜けて（キャラをすり抜けて）
左側もしくは下側から落とし穴イベントの所定の位置に行くと強制終了します

落ちた後、dbg.txtファイルには以下のログが記録されていました
（下側・左側どちらから行った場合でも同じログ）

[dbg] func_name:Event::chg_dir, line:1407 >>> id: 9520 not found

不要かもしれませんが、その状況を録画してみましたので
私のつたない文章での説明で分かりづらい場合はこちらをご覧ください

https://youtu.be/dz7eXxMygTU

**Comment by i7-FF7FC** [comment]
動画とかいう神過ぎる報告ありがとうございます:+1:
確認してみます！

**Comment by i7-FF7FC** [comment]
おっしゃるように、エアティファの当たり判定が抜けていたため、
該当ポイントに、右や下から入ることが可能になっていました。

落ちるスクリプト(don_corneo_end.txt)には、
左or上からしか入ることを想定していなかったため、
それ以外で突入するとevent ID 9520が生成されず、
その後「9520がないよー」というエラーが出る流れでした。

ここのエラーって、結構デバッグワープから遠く、
自分では発見しづらいポイントなのでメチャクチャ助かります。ありがとうございます！:smile:
