### ISSUE TITLE
作戦会議に遅れると最後に強制終了

### ISSUE THREAD

**Issue by ponyexs** [beta1139/ff7fc-develop#78]
v4.12a(2021/01/28 1:53版)です。

最初の爆破ミッション後のティファの店での一連のやり取りの最中、
地下アジトへ行く前に一旦店の外へ出てしまうと
一連のイベントの最後、翌日になるタイミングで強制終了します。

dbg.txtには以下のログが記載されました。
[dbg] func_name:Event::create_event_data_from_event_data, line:995 >>> event_id:2261 is already exist

再現性があるため動画を用意できたので必要に応じてご参照くださいませ
https://youtu.be/je7tSr8Pd6w

////////////////////////////////////////

何度かやり方を変えて試したところでは…

●問題なし
・バレットが客を追い出した後、クラウドは店へ行かず周囲の話を聞いたり武器屋へ行ったりと周囲を散策。
　その後店に入り、通常通りイベントを進める　→　問題なし

・バレットが客を追い出した後、すぐに店に入ってイベントを進める。
　なお花をティファ・マリンにあげたり、カウンターのティファと話さず地下に降りたり、
　歩く場所を変えてみたり…　など数パターンやってみましたが
　店の中だけでの行動ではいずれも強制終了せず翌日へと進めることができました。

●強制終了
・バレットたちが地下へ行った後、外に出て散策。
　街中はもちろん駅まで戻って駅員たちと話が変わらなくなるまで何度も会話。
　（それにしてもこんな細かいところまでしっかり再現されていますね。家から閉め出されているジョニーとか。さすが！）
　　また武器屋へ入って若者？に10ギル払って3階で休憩。
　　その後セブンスヘブンへ戻ってイベント再開→強制終了
　　なお店から出る前と散策から戻った後のそれぞれで
　　カウンターのティファに話す・話さず無視して地下へ、の両パターンをやりましたが状況には影響なし

・外に出て、街中と武器屋で会話。なお武器屋の3Fでは寝ない。駅にもいかない。→強制終了
・外に出て、街中の3人と会話。店に戻ってイベントの続き→強制終了
・外に出て、誰とも話さずすぐに店に戻る。イベント再開→強制終了

なので行動に原因は恐らく無く、ただ外へ出ることで発生するようです。

**Comment by i7-FF7FC** [comment]
これまた神報告ありがとうございます！
確認してみます。

**Comment by i7-FF7FC** [comment]
セブンスヘブンの出入りは、MAPエディターからではなく、
スクリプトでコントロールしているのですが
(ティファ加入前後でBGMを切り替えるため)、
その入り口付近に設置したBGM切り替えスクリプトを、
一旦kill(消滅)させることなく、一夜明ける際に再び生成してしまっていたので、
それが2重生成となり落ちていました。
ご報告ありがとうございました。

ちなみに切り替えスイッチは、出口一歩前に設置していたので、
正確には、外に出なくても発生していましたw
ただイベ途中のセブンスヘブン散策までやって下さるとは、
作ってて良かったなぁとしみじみ。。

**Comment by ponyexs** [comment]
お早い更新ありがとうございます。



せっかくの素晴らしい作品ですから
できる限りすべての要素を楽しみたいと思って
いろいろな遊び方を試みています。
レアセリフ・イベントまでしっかり作ってくださってますから
遊ばせてもらう側としては凄いテンション上がります！
ありがとうございます
