### ISSUE TITLE
無人の神羅ビルへ不法侵入

### ISSUE THREAD

**Issue by ponyexs** [beta1139/ff7fc-develop#79]
重箱の隅をつつくような感じにもなってしまい申し訳ありませんが、
私と同じ行動をとるような同類がいるかもしれないので一応ご報告…

/////////////////////////////////////

最初のカードキー（59Fの兵士戦）の入手前に右側のエレベーターを使用すると
60F以降が無人で全部屋オープン、そしてイベントなし状態になります。

最初にビルに乗り込んだときは右側のエレベーターはもちろん使用不可能ですが、
恐らくは59F到着が使用可能になるタイミングなんでしょうか。

エレベーターでも非常階段でもどちらから59Fまで乗り込んでも同じですが
59Fへ到着しても兵士たち（最初のカードキーを落とす相手）と戦わずに1Fへ引き返し、
1Fから右側のエレベーターに向かうと使用可能になっていました。

この状態で60Fに行くと、無人でさらに全部屋が通行可能です。
このまま進めて最上階に行ったり、60F奥の宝箱を開けたりすると強制終了。
[dbg] func_name:Event::open_door, line:1285 >>> id: 14050 not found
[dbg] func_name:Event::chg_dir, line:1407 >>> id: 11903 not found

　59Fに着いてすぐ引き返す人なんてまずいない、とは思いますが
　実際に私の場合、FF7インターナショナルにて
　正面突撃からのエレベーター連戦を経て59Fへ到着後、
　回復とセーブのためにわざわざビルの入口まで戻ったことがあります。
　同類がいたら危険…？

**Comment by i7-FF7FC** [comment]
いえ、まさのその重箱の隅をつついてくれるのが大変ありがたいです。
確認してきますー。

**Comment by i7-FF7FC** [comment]
おっしゃるように、59Fがエレベ－ター使用可能のトリガーになっており、
条件分岐が不十分だったので修正しました。ありがとうございます！
こういう行動をしたくなる心理は私も非常に分かります:smirk:

**Comment by i7-FF7FC** [comment]
追記
59Fに到着、且つカードキー60が無いとエレベータ作動しないようしたんですが、
よく考えるとカードキー60の有無を条件にすれば良かっただけなので、再修正しました。
(59F前にカードキー60を入手することは無いハズなので)

**Comment by i7-FF7FC** [comment]
さらに追記
いや、ビルで捕まったらカードキー没収されるみたいなので、
やっぱまずいですw
元の修正に戻します:dash:

**Comment by ponyexs** [comment]
修正ありがとうございます。
この処理に伴うと思われる別現象の発生を確認したので
Issueに書きました

…けれども、関連と思われるのでこちらに追記すればよかったですね (^_^;
すみません
