### ISSUE TITLE
マップ68バグ

### ISSUE THREAD

**Issue by ff7fc-translate** [beta1139/ff7fc-develop#8]
マップ68（5番街スラムとミドリ公園の間のマップ）で
x:19 y:11 の位置から右に移動してマップ外に出られてしまう。
一方通行で、ここからマップ内には戻れない。
x:20 y:17 の位置から左に移動してマップ内に戻れる。
これも一方通行で、ここからマップ外には出られない。

**Comment by i7-FF7FC** [comment]
修正しました。
で、マップのアタリ判定の修正は簡単なので、一応やり方書いときますね。

アタリ判定の付け方は、マップエディターの「EDIT TARGET」ってとこで、
「ATARI L(下層用)」もしくは「ATARI U(上層用)」を選んで、
右側一番上の「赤×」をクリックして、該当箇所をクリックするだけです。
今回は「上層→下層」なので、「ATARI U」の方です。
ちなみに、どこが上層、下層かを見る場合は、「ATARI T」を選べば分かります。
（D：下層、U：上層、M：中層）

また、アタリ判定を消す場合は、先ほどの「赤×」の左の空白（真っ黒な部分）を
クリックで再選択して、該当箇所のクリックすれば消えます。
注意点としては、「EDIT TARGET」で選択しているアタリ判定のみが対象ということです。
例えば、「ATARI L」のアタリ判定は、「ATARI L」を選択してないと消えませんし、
また「ATARI U」のアタリ判定は、「ATARI U」を選択してないと消えません。
