### ISSUE TITLE
脱出不可能（2021/01/29 23:47版）

### ISSUE THREAD

**Issue by ponyexs** [beta1139/ff7fc-develop#81]
追記2
1/30で修正済みの件でした。申し訳ございません。

-------------------
追記1（訂正）
1/30のバージョンで試してから再度ご報告いたします

------------------------------
2021/01/29版からの発生かと思います

神羅ビルから脱出するため、エアリス・バレット・レッドXIIIがエレベーターに乗り込む場面ですが、
エレベーターに乗ろうとすると『反応が無い…他のルートを探そう』メッセージが表示され使用不可能になっています。
（神羅ビル1Fの右側のエレベータの最初のメッセージと同じ）

2021/01/29 23:47版をニューゲームで進めている際に確認しましたが、
ひとつ前のデバッグセーブポイントから復帰しても
同じ現象が発生することを確認いたしました。

![ff7fcえれ](https://user-images.githubusercontent.com/76899650/106351062-15732080-631d-11eb-84a0-1e26a0231145.jpg)

**Comment by ponyexs** [comment]
すみません、こちらは一つ前のバージョンでしたね。
新しいバージョンで再度試してから再度ご報告いたします

**Comment by ponyexs** [comment]
1/30版で訂正されている件だったのを確認いたしました
お騒がせして申し訳ございません

**Comment by i7-FF7FC** [comment]
いえいいえ、こちらこそすれ違いになってすみません。
まさにRev879でこの画像状態になったのでw再び元に戻した次第です。
