### ISSUE TITLE
moveとslide_walkの歩行チップについて

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#84]
アニメーション組んでで分かったのですが、
「move_npc(char)」と「slide_walk_npc」とで、
それぞれ移動させる際に、フレーム毎によるキャラチップの参照先(右左)が、
違うことに気付きました。

詳しくは下記に記載しますが、
slide_walkで移動する場合は、全ての方向で移動開始時にデフォ(左)参照、
途中から右側のチップに移行します。

しかしmove～の場合は、
下と右移動はslidewalk～と同じ挙動、
上と左移動は移動開始時に右チップ参照、
途中からデフォ(左)に移行となっています。

この辺は、アニメーションさせる際に混乱してしまうので、
slide_walkとmove統一できないかなと。

ちなみにFF3の挙動を確認したところ、
こっちは下移動のみ、開始デフォ(左)→後半右で、
残る上/左/右移動は、開始右→後半デフォでした。
なんで下だけ違うのか謎ではありますが、
どうせ統一するなら、同じFF3スタイルを踏襲できないかなと。

***
:black_large_square:現slide_walk～のキャラチップ挙動（*数字はフレーム数）

:black_medium_small_square:SPEED：Fast
・全方向
　1～4：左(デフォ)
　5～8：右

:black_medium_small_square:SPEED：Normal、Slow
・全方向
　1～8：左(デフォ)
　9～16：右
　17～24：左(デフォ)
　25～32：右

***
:black_large_square:現move～のキャラチップ挙動

:black_medium_small_square:SPEED:Normal、Slow
・DOWN/RIGHT
　1～8：左(デフォ)
　9～16：右
　17～24：左(デフォ)
　25～32：右

・ UP/LEFT
　1～8：右
　9～16：左(デフォ)
　17～24：右
　25～32：左(デフォ)

:black_medium_small_square:SPEED:Fast
・ DOWN/RIGHT
　1～4：左(デフォ)
　5～8：右

・UP/LEFT
　1～4：右
　5～8：左(デフォ)

***
:black_large_square:FF3のキャラチップ挙動

:black_medium_small_square:SPEED：Normal、Slow
・DOWN
　1～8：左(デフォ)
　9～16：右
　17～24：左(デフォ)
　25～32：右

・ UP/LEFT/RIGHT
　1～8：右
　9～16：左(デフォ)
　17～24：右
　25～32：左(デフォ)

**Comment by i7-FF7FC** [comment]
追記：
FF3と同じに...と思ったけど、
アニメーションのことを考えたら、全方向同じにした方が都合が良いかも知れない。
全部開始時は右で途中から左のパターンが良いかも。

**Comment by beta1139** [comment]
全部開始時は右で途中から左のパターンにしました！

**Comment by i7-FF7FC** [comment]
ありがとうございます！ただ何かがおかしい。。
ちょっと確認中です。

**Comment by i7-FF7FC** [comment]
移動時のドットのずらし処理が以前と同じフレームのままなので、
move_right時とmove_down時は、左側のチップにかかっているようです。

あとslide_walkで上以外に移動すると、
途中まで良いんですが、最終的に右になってます。(さらにしばらく待つとデフォに戻る)

**Comment by i7-FF7FC** [comment]
追記
あとすみません、FF3改めて調べたら、
DOWNとRIGHTが同じ仕様で、最初デフォで途中右でした。
つまり以前の一番上のFF7FCと同じでした。。
これ変えない方がいいですかね。。

**Comment by i7-FF7FC** [comment]
うーん、複数のチップでアニメーション組む際は、
全方向同じ処理にした方が都合が良いんだけど、
FF3の移動モーションも踏襲したい・・・。

となると、これまでと同じようにmove時とslide時は、
敢えて違う動作をするようにして、使い分けた方が逆に良いんだろうか…？

**Comment by i7-FF7FC** [comment]
本当に申し訳ありません！
↓以前の挙動に戻してもらえないでしょうか:bow::bow::bow:
moveのDown/Rightは、デフォ(左)スタート→途中右→デフォに戻る
moveのUp/Leftは、右スタート→途中左→そのままデフォ
slidewalkは全方向、デフォスタート→途中右→デフォに戻る

slidewalk時にmoveのようなずらし処理を入れたかったのですが、
個別にoffsetで対処していこうかなと思った次第です。。

**Comment by beta1139** [comment]
戻しました！

**Comment by i7-FF7FC** [comment]
勝手な独り相撲に巻き込む形になってスミマセン！
お陰でもう少しで回想前半終わりそうです。

そんな中、もう1点気付いたことがあり大変恐縮なのですが、
slide_walkのslow時のみ、16フレーム毎にチップが切り替わっているようなので、
これをmoveと同じ8フレーム毎にできないでしょうか？
(正確にはsleep7-8-1みたいな処理になってるのかな？)

他のスピードだと、moveとslidewalkの切り替わるタイミングは同じなので、
これはたぶん支障がないハズ・・・

|    |  move |  slidewalk  |
| ---- | ---- |  ---- |
|  fast  |  4 |  4  |
|  normal |  8   |  8  |
|  slow |  8  |  16  |

**Comment by beta1139** [comment]
slide_walkのslowをmoveと同じ8フレーム毎にしました！

**Comment by i7-FF7FC** [comment]
ありがとうございます、解決しました！
