### ISSUE TITLE
透明度のスクリプト

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#91]
お時間ある時で構いません:coffee:
現在、画像の透明度に関するスクリプトは、
set_image～、inc_image、dec_image～の3種類がありますが、
指定した分だけ増減する命令を実装できないでしょうか？
今やっているスクリプトがだいぶシンプルに出来るなぁと思いまして。

**Comment by beta1139** [comment]
お～。近いうちに見ておきます～

**Comment by i7-FF7FC** [comment]
ありがとうございます！
で早速試してみたところ、sub~を打つと落ちるっぽいです。

エラー：「unknown opecode: sub_image_alpha」
***
(一応参考スクリプト)
draw_image 000 0 8 0 0 256 224 1 event/black.png
set_image_alpha 000 0
wait_key_push_edge a
add_image_alpha 000 50
sleep 16
wait_key_push_edge a
sub_image_alpha 000 10

**Comment by beta1139** [comment]
すみません、実装ミスってました。
修正しました。お手数お掛けして申し訳ありません:pray:

**Comment by i7-FF7FC** [comment]
お疲れ様ですー。
sub~だと透明度が0になるようです。

***
draw_image 000 0 8 0 0 256 224 1 event/black.png
set_image_alpha 000 0
wait_key_push_edge a
add_image_alpha 000 100
sleep 16
wait_key_push_edge a
sub_image_alpha 000 10
sleep 16

**Comment by beta1139** [comment]
ああごめんなさい。今度こそ大丈夫、なはず

**Comment by i7-FF7FC** [comment]
成功しましたw
スクリプトがスッキリして気持ちいー！
ありがとうございます:smile:
