### ISSUE TITLE
列車での会話時のずれ＆先頭エアリスで強制終了（バグ ）

### ISSUE THREAD

**Issue by ponyexs** [beta1139/ff7fc-develop#93]
Labelの設定ができないようなので括弧書きでバグ表示の代わりとさせてください(^^;

確認はrev.895です。2つ遭遇しました

1.
最初の魔晄炉爆破後。帰りの列車の中でウェッジと話している間
ずっと右や左へキーを入れたままにしておくと
選択肢を選んだ瞬間にプレイヤー（透明）がその方向へ1歩移動します。

このときウェッジの前にはオブジェクト化したクラウドがそのまま残っています。
会話終了後はプレイヤーは透明のまま自由に移動・会話が可能です。

透明のままジェシーに話しかけると会話後にクラウドの姿に戻ります。
オブジェクト化したクラウドもそこに残ったままです。

そのままバレットと会話して列車から降りれば正常に戻ります。

この現象ですが起きない場合もあったので何か条件があるのかもしれません

起きた際の動画はこれです
[https://youtu.be/7FpzEKZTIXI](https://youtu.be/7FpzEKZTIXI)

----------------------

2.
柱攻防戦の開始前
移動表示用のキャラをエアリスにしていた場合に表示が狂います。

表示キャラをエアリスにした状態で柱まで行くと
柱へ到着した時の一連の会話イベントが終了した後
プレイヤーキャラ表示が目まぐるしく変わり透明になります。
この状態で左右のマップ切り替えポイントへ行くとゲームが落ちます。
ログは
[dbg] func_name:Event::chg_dir, line:1437 >>> id: 1921 not found

なお同じ状態で
左右ではなく下へ行くと、ティファからの警告を2連続でもらいます。
その後左右のマップ切り替えポイントまで行くとティファから一度警告をもらってから強制終了。
ログは変化していました。
[dbg] func_name:Event::to_move_event, line:1390 >>> id: 1921, dir: 0

実際の動画はこちらです
[https://youtu.be/uWMaTqjcbo4](https://youtu.be/uWMaTqjcbo4)

なお余談ではありますが
移動表示キャラをティファにしていた場合は問題は発生しません。

ただ一応表示だけのことですが
マップ切り替えポイントに行こうとするときの警告メッセージが
喋る方も受ける方も両方ティファになります

**Comment by i7-FF7FC** [comment]
> 選択肢を選んだ瞬間にプレイヤー（透明）がその方向へ1歩移動します。

この列車乗車時は、通常のイベントと平行して、
列車の揺れを終始動かしているので、その関係ですね。。
ちょっと見てみます。

**Comment by i7-FF7FC** [comment]
今回使っている"非同期"のスクリプトを使うと、
本来なら動けないタイミングでもキャラを操作できるメリット
(最初の魔晄炉でビッグス達が動きながらクラウドも操作できる等）がある一方、
逆に動いてはいけないタイミングでも動けてしまうリスクもあって、今回はそのパターンでした。

詳しく言うと、問題の箇所で使っていた
「wait_target_talked ～」っていうスクリプトが若干曲者でして、
発動までに一瞬タイムラグが発生するっぽいので、
ボタン押しっぱだとその間動けてしまう問題があるんですよね:cry:

そういうのもあって、基本的に非同期イベ中は、
上記命令を自重するようにしていたんですが、
初期に打ったのもあり漏れていた様です。

なので、ラグが発生しない
「wait_target_talk ～」という似たような命令に変更しました。
(ちなみにジェシーやバレットでも同様のバグが発生しておりました)

たぶん何のこっちゃ分からない部分も多いと思いますが、
半分自分用のメモなので、気にしないでくださいw

**Comment by i7-FF7FC** [comment]
柱イベ前に強制的にクラウドに戻るよう修正しました:smiley:

実はキャラ表示の切り替えって、
ある時からデフォ無効で行きましょうか、みたいになったんですよね。
(クラウド表示前提のイベントがほとんどなので)

ただ個人的には、非常に惜しい機能だったので、
イベントに支障がない範囲では、敢えてONに切り替えてたんですが、
気を付けないとこういう問題が発生しますね～～。。。
私自身最近、この表示切替忘れていたのでw、
改めて思い出させてくれて感謝でございます！:pray:

**Comment by ponyexs** [comment]
修正ありがとうございました🙇

そういえば最初の魔晄炉爆破のシーンで
ジェシー達が動く中、クラウドも自由に歩けたのみて
感動したのを思い出しました😤

遊ぶ前はファミコンなどでは当たり前の
キャラが画面内から去ってからプレイヤー行動開始、
かと思っていたので
実際に走るアバランチに混じって自由に動けるところが
画期的で衝撃的でした🤩

フィールド上の表示キャラの切り替えは
ゲームを遊ぶ上では気分的にあると嬉しいですね♪
でも不都合が生じる可能性があるのは難しいところですね
作るうえでの大変さを考えると安易に搭載してくれーとは言いにくいところです（言ってるけど😓

**Comment by i7-FF7FC** [comment]
> フィールド上の表示キャラの切り替えは
> ゲームを遊ぶ上では気分的にあると嬉しいですね♪

そうですよね、私もそう思っているので、
今後もイベに支障がなさそうなら、できるだけONにしたいところではあります:grin:

ということで、Betaさんにクラウドを外せないようにしていただいたので、
カーム回想後は、キャラチャンジ機能をONにしてみました。
宿屋に泊まったり等、イベ中は一時的にクラウドに戻りますが、
その後は元に戻るようになってると思います(たぶん！)

**Comment by ponyexs** [comment]
ありがとうございます

宿屋のほか、
『てがとどかない』ところでも
確認させていただきました！
