### ISSUE TITLE
パーティでクラウドのみ固定

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#94]
ponyexsさんのご報告で思い出したのですが、
今後は常時PHSでPTを組み替えられるようになったので、
先頭をクラウド以外にすることが可能なんですよね。

なのでクラウドのみPT固定に出来ませんでしょうか？:thinking:
原作も終盤のシドが主人公になる時以外は外せませんし。

**Comment by beta1139** [comment]
そうですね。その方がイベント作成で都合が良さそうですね

**Comment by beta1139** [comment]
PHSでクラウドをPTから外せないように修正しておきました！

**Comment by i7-FF7FC** [comment]
ありがとうございます、確認しました！
