### ISSUE TITLE
スタートポジション

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#95]
お尋ねします。
デフォのゲーム開始ポジションって変えられますかね？
config_CS.exeから変更しても、更新データ扱いにならないので、
コミットできないんですよね:disappointed_relieved:。。

最初のマップ(001)を
オープニングシーンと繋がるように左にちょびっと広げたくて。

**Comment by beta1139** [comment]
あれ、`ini.bin` が書き換わるはずですけどね

![タイトルなし](https://user-images.githubusercontent.com/11572021/114428804-9e4ce900-9bf7-11eb-9887-9d0ec8b0619e.png)

**Comment by i7-FF7FC** [comment]
ああーbinが変わるのかー
configのアイコン変わらないなぁと勘違いしてました。
すみませんありがとうございます！
