### ISSUE TITLE
カウントダウン中に戦闘

### ISSUE THREAD

**Issue by i7-FF7FC** [beta1139/ff7fc-develop#96]
fake_countdown中にエンカして、
戦闘中にタイムアウトすると、
スクリプト終了後に画面が一瞬暗転してしまいます:cry:

---ichibangai_station_baret.txt---
start_fake_countdown_sec 10
chg_char_state_move
encount 0
wait_fake_countover
msg カウントしゅうりょう
end

あと、カウント中(fake含む)に全滅すると、
コンティニュー後もタイムが表示されたままになるので、
全滅時にイレース処理していただけると幸いですー。

**Comment by beta1139** [comment]
ちょっと余裕がない
時間できたらやりますー

**Comment by i7-FF7FC** [comment]
了解ですー
こちらもやっては休みの繰り返しですから、のんびり行きましょう！

一応現状報告。
とりあえずチョコボの実装が無いと以降は作れなさそうなので、私もしばらく放置してたんですが、
ふとスクリプトで強引にやれないなこともないなと、ちょっと思い立ってまた遊び始めたところです。
最終的にはプログラムでやらないと無理な部分もあるので、
とりあえずの暫定みたいな感じで進めております:dash:
ミドガルズ:snake:はまだノープランす。

**Comment by beta1139** [comment]
修正しておきました！

**Comment by i7-FF7FC** [comment]
確認遅れましたーすみません。
暗転処理は上手く行きました、ありがとう御座います！

フェイク・カウント中に全滅した際の挙動ですが、
その後ニューゲームで再開すると、
タイムが「00：00」と表示され、「ばくはにまきこまれて～」と
フェイクじゃない方のカウントダウンが発動し、再び全滅してしまいます。

----全滅用スクリプト----
wait_same_pos
start_fake_countdown_sec 60
encount 20

**Comment by beta1139** [comment]
すみません。修正しました

**Comment by i7-FF7FC** [comment]
おぉー素早いご対応不意打ちでしたwありがとうございます！
アレですね、、今度は再開時にフェイクカウントが表示されなくなってますね。。
単に表示されていないだけなのか、実際に発動してないのかはちょっと分かり兼ねますが。

**Comment by i7-FF7FC** [comment]
今試したら、内部では発動している模様です。
なのでカウント表示だけされてないっぽいですね。

**Comment by beta1139** [comment]
今度こそ。たぶん直りました。。

**Comment by i7-FF7FC** [comment]
w
お疲れ様です直りました！:grin::pray:

**Comment by i7-FF7FC** [comment]
派生バグっぽいのに遭遇したので改めて追記です。
「draw_fake_countdown off」を使ったイベントで、
カウントウィンドウが表示されたままになっておりました。

正確には、
「start_fake_countdown」の"前"に打った場合で発生し、
"後"に打った場合は問題ありません。

***
(例)これだと消えない
draw_fake_countdown off
start_fake_countdown_sec 10

これだとちゃんと消える
start_fake_countdown_sec 10
draw_fake_countdown off

**Comment by beta1139** [comment]
修正しました。たぶん、大丈夫。。。

**Comment by i7-FF7FC** [comment]
お疲れ様です。
カウントオフは機能するようになったんですが、
今度はまた全滅＆再開後にカウントが表示されなくなってるようです。
うーん難しい:dizzy_face:

**Comment by beta1139** [comment]
何度も確認させてすみません。今度こそ。。

**Comment by i7-FF7FC** [comment]
いえいえ、再現可能なバグが見つかるのは
ある意味良いことなのでお気になさらずにー。
一通り試しましたが問題ありませんでした！
乙ありでございます！:v:
