### ISSUE TITLE
今のバーションは プレーするできません

### ISSUE THREAD

**Issue by sniperhgy** [beta1139/ff7fc-develop#97]
今のバーションを プレーしてみます。起動できますが、 ’ニューゲーム’を選ぶ、ゲームは自動に閉めます。

**Comment by beta1139** [comment]
はい。スクリプトファイルを無効化しています。
最新のコミットを確認できますか？
https://github.com/beta1139/ff7fc-develop/commit/fd01e798a947b9c76dcfdf41944f04f33cc89f53
この修正を戻せばプレーできます

**Comment by sniperhgy** [comment]
お返事をありがとうございます。
英語のバーションのスクリプトファイル （ff7fc-develop-master\event\script_e\001\ichibangai_station_baret.txt）は 日本語のバーションのフォルダに複製してみました。 プレーできますが  言葉はおかしいとなりました😄
